### ISSUE TITLE
When I completed a practice, it displays.

### ISSUE THREAD

**Issue by AurevoirXavier** [aradzie/keybr.com#318]
```
Oh no, something bad has happened!

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (code=8) (type=[object DOMException])
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ul (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:337165)
    at fl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338411)
    at dl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338674)
    at fl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338561)
    at dl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338674)
    at fl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338561)
    at dl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338871)
    at fl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338561)
    at dl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338871)
    at fl (https://www.keybr.com/assets/a02c11c94071c1bd.js:2:338561)
```

**Comment by aradzie** [comment]
This error occurs somewhere in the `react-dom` library.

```json
{
  source: 'webpack://keybr.com/node_modules/react-dom/cjs/react-dom.production.min.js',
  line: 248,
  column: 288,
  name: 'removeChild'
}
```

So, that is not a keybr error.

What is your browser and OS? (Please share the link from this page https://www.whatismybrowser.com/) 
Do you have any browser extensions installed?

**Comment by AurevoirXavier** [comment]
But it would be better if I could make them compatible, then I wouldn't have to disable it every time.

**Comment by aradzie** [comment]
> But it would be better if could make them compatible, then I wouldn't have to disable it every time.

I think you should report this error to the extension authors. It's their job to make sure that their extension does not break websites!
