### ISSUE TITLE
TypeError: Missing env property 'AUTH_GOOGLE_CLIENT_ID

### ISSUE THREAD

**Issue by baicaofa** [aradzie/keybr.com#342]
I have deployed it locally and there were no errors during the testing process. However, I found that the login system doesn't work. Logging in via email, Google, Microsoft, or Facebook is not available. Judging from the error messages, do I need to configure my own platform keys? And where should I configure them?

`TypeError: Missing env property 'AUTH_GOOGLE_CLIENT_ID'
    at Function.getValue (webpack://keybr.com/packages/keybr-config/lib/env.ts:86:15)
    at Function.getString (webpack://keybr.com/packages/keybr-config/lib/env.ts:47:16)
    at AuthModule.provideGoogleAdapter (webpack://keybr.com/packages/server/lib/app/auth/module.ts:21:26)
    at makeValue (webpack://keybr.com/node_modules/@fastr/invert/src/impl/binding/provider.ts:14:22)
    at ProviderBinding.getValue (webpack://keybr.com/node_modules/@fastr/invert/src/impl/binding/provider.ts:19:31)
    at Container.get (webpack://keybr.com/node_modules/@fastr/invert/src/container.ts:77:22)
    at Container.get (webpack://keybr.com/node_modules/@fastr/invert/src/container.ts:80:27)
    at pAdapter (webpack://keybr.com/packages/server/lib/app/auth/pipe.ts:19:22)
    at getArgs (webpack://keybr.com/node_modules/@fastr/controller/src/route.ts:89:21)
    at async <anonymous> (webpack://keybr.com/node_modules/@fastr/controller/src/route.ts:72:18)`

**Comment by aradzie** [comment]
Yes, you have to provide your own IDs. These configuration values are secret and I cannot share mine with you.

The process of integration is different for each third party service.
If you want to connect with google, start from reading these documents
https://support.google.com/cloud/answer/6158849?hl=en
https://developers.google.com/identity/protocols/oauth2

**Comment by baicaofa** [comment]
> You may also want to run a local email server for testing purposes. Ask ChatGPT how to do this.

Thank you for your answer. In which file should I fill in my configuration? I've found a location: [keybr.com](https://keybr.com/)\packages\test-env-server\lib\index.ts, and I've written my own secret keys on GOOGLE ID and SECRET, but it doesn't seem to work.

**Comment by aradzie** [comment]
You should update an .env file.

Keybr tries to load [these env files](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-config/lib/env.ts#L12).

I suggest you update this file `/etc/keybr/env`. Put all secret key/value pairs there.

**Comment by baicaofa** [comment]
> You should update an .env file.
> 
> Keybr tries to load [these env files](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-config/lib/env.ts#L12).
> 
> I suggest you update this file `/etc/keybr/env`. Put all secret key/value pairs there.

Thanks. I'll update the.env file, Have a try.

**Comment by baicaofa** [comment]
> You should update an .env file.
> 
> Keybr tries to load [these env files](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-config/lib/env.ts#L12).
> 
> I suggest you update this file `/etc/keybr/env`. Put all secret key/value pairs there.

When I executed env DATABASE_CLIENT=sqlite npm test, there were no error messages reported. However, it seems that the database wasn't created successfully. There is a file named database.sqlite in the ~/.local/state/keybr/ directory, but it's blank. Is this normal?
The following error message appears when clicking on "Sign-In with E-mail":
`SqliteError: delete from `user_login_request` where `created_at` < '2024-12-06 00:56:12.518' - no such table: user_login_request
    at Database.prepare (/home/eric/keybr.com/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (webpack://keybr.com/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:1)
    at executeQuery (webpack://keybr.com/node_modules/knex/lib/execution/internal/query-executioner.js:37:1)
    at Client_BetterSQLite3.query (webpack://keybr.com/node_modules/knex/lib/client.js:154:1)
    at Runner.query (webpack://keybr.com/node_modules/knex/lib/execution/runner.js:141:1)
    at ensureConnectionCallback (webpack://keybr.com/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:1)
    at Runner.ensureConnection (webpack://keybr.com/node_modules/knex/lib/execution/runner.js:318:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Runner.run (webpack://keybr.com/node_modules/knex/lib/execution/runner.js:30:1)
    at async QueryBuilder.execute (webpack://keybr.com/node_modules/objection/lib/queryBuilder/QueryBuilder.js:446:1) {
  code: 'SQLITE_ERROR'`

**Comment by aradzie** [comment]
Yes, tests use memory-only database. This is the fastest way. No database files are created in tests. 

There is a script which creates a local SQLite database for the development environment -- `packages/devenv/lib/initdb.ts` please read about it in the docs -- https://github.com/aradzie/keybr.com/blob/master/docs/getting_started.md

> > You should update an .env file.
> > Keybr tries to load [these env files](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-config/lib/env.ts#L12).
> > I suggest you update this file `/etc/keybr/env`. Put all secret key/value pairs there.
> 
> When I executed env DATABASE_CLIENT=sqlite npm test, there were no error messages reported. However, it seems that the database wasn't created successfully. There is a file named database.sqlite in the ~/.local/state/keybr/ directory, but it's blank. Is this normal?
